name: Feature request
description: 提议一个新功能
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: 使用场景
      description: 你希望解决什么问题？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 建议方案
    validations:
      required: true
